name: Create environment

on: [push, workflow_dispatch]

env:
  RESOURCE-GROUP: Tahira1-rg
  LOCATION: westeurope
  TEMPLATE-FILE: web1.bicep
  SUBSCRIPTION-ID: ${{ secrets.subscriptionId }}
  WEBAPP-NAME: az400-webapp-tahira00test
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  APP_ARTIFACT_LOCATION: "build" # location of client code build output

jobs:
  create-environment:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI Create resource group  
      uses: Azure/cli@1.0.4
      with:
        inlineScript: az group create -n ${{ env.RESOURCE-GROUP }} -l ${{ env.LOCATION }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: Tahira-rg
        template: web1.bicep
        parameters: main1.parameters.json
    # # Publish website to Azure App Service (WebApp)
    # - name: Publish Website to WebApp
    #   uses: Azure/static-web-apps-deploy@v1
    #   with:
    #     app-name: ${{ env.WEBAPP-NAME  }}
    #     package: .net-app


    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        app-name: ${{ env.WEBAPP-NAME  }}
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: ${{ env.APP_LOCATION }}
        api_location: ${{ env.API_LOCATION }}
        app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}